name: Build Mac App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # MUDANÇA AQUI: Usamos 'macos-13' para forçar processador Intel (x86_64)
    # Isso garante compatibilidade com TODOS os Macs (velhos e novos).
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar Dependencias
      run: |
        pip install flask flask-cors flask-login pywebview nuitka pyobjc-core pyobjc-framework-Cocoa ordered-set

    - name: Compilar com Nuitka
      run: |
        # O Nuitka vai gerar o backend.app na raiz
        python -m nuitka --standalone --macos-create-app-bundle --assume-yes-for-downloads --include-data-file=sistema.html=sistema.html --include-data-file=tv.html=tv.html backend.py

    - name: Listar arquivos (Debug)
      run: ls -la

    - name: Compactar o App
      run: |
        # Zipamos o app gerado
        zip -r ClinicaSysMac_Intel.zip backend.app

    - name: Upload do Arquivo Final
      uses: actions/upload-artifact@v4
      with:
        name: ClinicaSys-Mac-Intel
        path: ClinicaSysMac_Intel.zip
