name: Build Mac App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar Dependencias
      run: |
        # Adicionamos flask-cors, flask-login e ordered-set que faltavam
        pip install flask flask-cors flask-login pywebview nuitka pyobjc-core pyobjc-framework-Cocoa ordered-set

    - name: Compilar com Nuitka
      run: |
        # Adicionei --assume-yes-for-downloads para ele não travar pedindo confirmação
        python -m nuitka --standalone --macos-create-app-bundle --assume-yes-for-downloads --enable-plugin=flask --include-data-file=sistema.html=sistema.html --include-data-file=tv.html=tv.html backend.py

    - name: Compactar o App
      run: |
        cd backend.dist
        zip -r ClinicaSysMac.zip backend.app

    - name: Upload do Arquivo Final
      uses: actions/upload-artifact@v4
      with:
        name: ClinicaSys-Mac-Build
        path: backend.dist/ClinicaSysMac.zip
