name: Build Mac App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Mantemos macos-13 para garantir compatibilidade com Intel e M1/M2
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # MUDANÇA 1: Usamos Python 3.11 que corrige o problema de links quebrados
        python-version: "3.11"

    - name: Instalar Dependencias
      run: |
        # MUDANÇA 2: Forçamos a reinstalação do OpenSSL para corrigir o arquivo que faltava
        brew install openssl@3
        pip install flask flask-cors flask-login pywebview nuitka pyobjc-core pyobjc-framework-Cocoa ordered-set

    - name: Compilar com Nuitka
      run: |
        python -m nuitka --standalone --macos-create-app-bundle --assume-yes-for-downloads --include-data-file=sistema.html=sistema.html --include-data-file=tv.html=tv.html backend.py

    - name: Listar arquivos (Debug)
      run: ls -la

    - name: Compactar o App
      run: |
        zip -r ClinicaSysMac_Intel.zip backend.app

    - name: Upload do Arquivo Final
      uses: actions/upload-artifact@v4
      with:
        name: ClinicaSys-Mac-Intel
        path: ClinicaSysMac_Intel.zip
