name: Build Mac App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar Dependencias
      run: |
        pip install flask flask-cors flask-login pywebview nuitka pyobjc-core pyobjc-framework-Cocoa ordered-set

    - name: Compilar com Nuitka
      run: |
        # Aqui ele LE o backend.py e CRIA o backend.app
        python -m nuitka --standalone --macos-create-app-bundle --assume-yes-for-downloads --include-data-file=sistema.html=sistema.html --include-data-file=tv.html=tv.html backend.py

    - name: Listar arquivos (Para conferÃªncia no log)
      run: ls -la

    - name: Compactar o App
      run: |
        # Aqui ele pega o backend.app (o programa gerado) e guarda no zip
        zip -r ClinicaSysMac.zip backend.app

    - name: Upload do Arquivo Final
      uses: actions/upload-artifact@v4
      with:
        name: ClinicaSys-Mac-Build
        path: ClinicaSysMac.zip
